features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: 'public://favicon_3.png'
favicon:
  use_default: 1
  path: themes/custom/mortenson/favicon.png
  mimetype: image/png
