#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-andyux01-tomebookis-bdac6lqfvwu.ws-us114.gitpod.io
- 8025-andyux01-tomebookis-bdac6lqfvwu.ws-us114.gitpod.io
- 8036-andyux01-tomebookis-bdac6lqfvwu.ws-us114.gitpod.io
